import 'package:firebase_core/firebase_core.dart';

/// One-time Firebase start-up for CricScore — currently a deliberate no-op.
///
/// WHY THIS IS EMPTY
/// -----------------
/// `Firebase.initializeApp()` needs `lib/firebase_options.dart`, which is
/// generated by `flutterfire configure`. That command authenticates with the
/// project owner's own Google account and must run on their machine
/// (ADR 0002 §Consequences, `docs/12-cloud-sync-plan.md` §0), so the file does
/// not exist in this repo yet. Importing a file that is not there would stop
/// the whole app compiling, so every Firebase reference is kept behind this
/// single function.
///
/// Until it is switched on, [isFirebaseInitialised] stays `false`, the auth
/// layer reports "signed out", and the app behaves exactly as it does today:
/// local-only, offline-first, no account required.
///
/// TODO(firebase-setup): once the owner has run `flutterfire configure`,
/// activate cloud sync by:
///   1. adding `import '../../firebase_options.dart';` at the top of this file;
///   2. replacing the body below with:
///        if (Firebase.apps.isNotEmpty) return;
///        await Firebase.initializeApp(
///          options: DefaultFirebaseOptions.currentPlatform,
///        );
///   3. calling it from `lib/main.dart` before `runApp`:
///        WidgetsFlutterBinding.ensureInitialized();
///        await initializeFirebase();
///      (keep it in a try/catch — a failed init must not block local scoring).
///
/// Nothing else in the auth stack needs to change: `FirebaseAuthService` picks
/// up the initialised app automatically via [isFirebaseInitialised].
Future<void> initializeFirebase() async {
  // Intentionally does nothing until `firebase_options.dart` exists.
}

/// Whether a Firebase app is live in this process.
///
/// Reads the in-memory app registry only — no platform channel, no network — so
/// it is safe to call from plain `flutter test` runs.
bool isFirebaseInitialised() => Firebase.apps.isNotEmpty;
